### ISSUE TITLE
String expression parsing fails

### ISSUE THREAD

**Issue by doblak** [emmanueltouzery/ng-typeview#1]
Using {{ 'a' + 'b' }} in view results in failed view parsing.

So does {{ 'a' + someValue }}, but does not with {{ someValue + 'a' }}.

Will prepare a pull PR with a fix.

**Comment by emmanueltouzery** [comment]
thanks for the PR! applied & published 0.0.7 on npm.

**Comment by doblak** [comment]
This is not the same issue as PR provided previously. Please reopen, will provide a PR for this specific issue.

**Comment by emmanueltouzery** [comment]
oops sorry :-)
