### ISSUE TITLE
@types/parsimmon@1.3.0 dependency not found on npm, version needs to be updated 

### ISSUE THREAD

**Issue by jacalata** [emmanueltouzery/ng-typeview#13]
c:\dev\vizportalclient>npm install --save-dev ng-typeview
npm ERR! code E404
npm ERR! 404 Not Found: @types/parsimmon@1.3.0

@types/parsimmon on npm:
https://www.npmjs.com/package/@types/parsimmon

**Comment by emmanueltouzery** [comment]
hmm this is a little baffling. types/parsimmon 1.3.0 does exist, it's also
seen on the npm page.

i tried installing ng-typeview in a blank folder now and it worked:

$ npm install ng-typeview
npm WARN saveError ENOENT: no such file or directory, open
'/home/emmanuel/dfjdkfd/package.json'
npm notice created a lockfile as package-lock.json. You should commit this
file.
npm WARN enoent ENOENT: no such file or directory, open
'/home/emmanuel/dfjdkfd/package.json'
npm WARN dfjdkfd No description
npm WARN dfjdkfd No repository field.
npm WARN dfjdkfd No README data
npm WARN dfjdkfd No license field.

+ ng-typeview@0.0.40
added 36 packages in 9.274s


can you try the same, installing in an empty folder? Which version of npm
do you have (I have 5.2.0)?

**Comment by emmanueltouzery** [comment]
i see the version there:
https://www.npmjs.com/package/@types/parsimmon/v/1.3.0

otherwise i have nothing against updating the version of the dependency, for sure.

**Comment by emmanueltouzery** [comment]
closing, this looks OK
