### ISSUE TITLE
Issues with a couple expressions

### ISSUE THREAD

**Issue by jlogar** [emmanueltouzery/ng-typeview#8]
Seems to have problems with:
- `<div>${{(card.storedValue/100).toFixed(2)}}</div>`
- `<img ng-src="{{cardPhoto}}" />`

**Comment by emmanueltouzery** [comment]
For the second you just don't need the {{}}. Just remove them.

The first.. Yeah will fix.

**Comment by jlogar** [comment]
silly me. Trusting the author...

Oh, and there's another:
`<select id="type" class="form-control" ng-model="status.selectedStatus" required ng-options="(status| translate) for status in status.list"></select>`

**Comment by emmanueltouzery** [comment]
yeah in this third expression you can also remove the brackets too. they just make explicit the priority which was already the same. but yeah, ideally ng-typeview would tolerate them anyway. likely the fix for toFix will also fix that, in both cases it's about bracketing.

**Comment by emmanueltouzery** [comment]
presumably remove brackets from examples 2 & 3. For example 1, for now I guess you can make a function in the controller & call it from the view... it's a tricky one :-(

**Comment by emmanueltouzery** [comment]
ok released 0.0.10 which fixes the `toFixed(2)` issue. For the other two, just remove the brackets (typeview may parse them one day, but it's low-priority as the brackets really are not necessary).
